# Generated by Django 2.2.6 on 2019-10-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_DB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coords', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('n_to', models.CharField(max_length=20, null=True)),
                ('s_to', models.CharField(max_length=20, null=True)),
                ('e_to', models.CharField(max_length=20, null=True)),
                ('w_to', models.CharField(max_length=20, null=True)),
                ('u_to', models.CharField(max_length=20, null=True)),
                ('d_to', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notes.note',),
        ),
    ]
